/* added constant string for button, text */
export default {
    edit: 'Edit',
    submit: 'Submit',
    support: 'Live Support',
    bankName: 'Qatar Development Bank',
    readMore: 'Read More...',
    guest: 'Guest',
    title: 'DashBoard Unit Testing',
    body: 'This screen is just to unit testing demo',
    all: 'All',
    overview: 'OverView',
    calender: 'Calender',
    scheduleActions: 'Schedule Actions',
    liveAlerts: 'LiveAlerts',
    latest: 'Latest',
    archived: 'Archieved',
    dashBoardHeaderTitle: 'Dashboards',
    blogsHeaderTitle: 'Blogs',
    serverdownError: 'Server down. Please try after some time',
    noData: 'No Data Available',
}
